### ISSUE TITLE
Check if SCO2529 really is a catalase

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#100]
### Description of the issue:
Uniprot annotation is metalloproteinase, and the gene expression trends are very different from teh other catalase. It is possible that we should remove this gene from the catalase function. 

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by edkerk** [comment]
According to [StrepDB](http://strepdb.streptomyces.org.uk/cgi-bin/dc3.pl?accession=AL645882&serial=2516&width=900&start=2723099&end=2733099&iorm=map) the annotation is indeed more likely to be metalloproteinase. The gene association for reaction `CAT` will be modified to remove this gene.
