### ISSUE TITLE
Fix duplicated reactions

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#104]
### Description of the issue:
The following reactions are duplicated in terms of substrates  / products (but not gene annotation):
- GABTA and ABPYRATA
- CA2abc1 and AMEt

Figure out which one of these that should be deleted / modified / kept

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [ ] E.g. generate script for performing curation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by sulheim** [comment]
# About the reactions
## 1. ABPYRATA
    - name: 4-aminobutyrate aminotransferase
    - metabolites:
      - 4abut_c: -1.0
      - ala__L_c: 1.0
      - pyr_c: -1.0
      - sucsal_c: 1.0
    - gene_reaction_rule: SCO5676 or SCO7034
    - ec-code: 2.6.1.19
    - kegg.reaction: R10178
The [EC-code and gene annotations](https://www.genome.jp/dbget-bin/www_bget?ec:2.6.1.19) matches [R01648](https://www.genome.jp/dbget-bin/www_bget?rn:R01648) and not R10178. However, since R01648 also is present in the model already (id: ABTA), I suggest to delete this reaction.

## 2. GABTA
    - gene_reaction_rule: SCO5655
    - biocyc: RXN-6902
    - ec-code: 2.6.1.96
Keep this reaction in the model and annotate it with R10178. 

## 3. CA2abc1
    - name: calcium-transporting ATPase
    - metabolites:
     - adp_c: 1.0
     - atp_c: -1.0
     - ca2_c: 1.0
     - ca2_e: -1.0
     - h2o_c: -1.0
     - h_c: 1.0
     - pi_c: 1.0
    - gene_reaction_rule: SCO3216 or SCO4332
    - biocyc: 3.6.3.8-RXN
    - ec-code: 3.6.3.8
    - metanetx.reaction: MNXR96435

Keep this reaction as is

**Comment by edkerk** [comment]
I agree, remove (1), update (2) and keep (3). For (4), are TRIC transporters active (using ATP) and transporting more than just Ca2+? This is not so clear from the provided link.
