### ISSUE TITLE
Unclear what the different model files represent

### ISSUE THREAD

**Issue by smoretti** [SysBioChalmers/Sco-GEM#110]
We wonder what is the "official" SBML Sco-GEM model in the ModelFiles/xml/ repository.

XML/SBML files have different size, different last modification time, and for some of them a cryptic name.

**Comment by edkerk** [comment]
`Sco-GEM.xml` is the "official" Sco-GEM. The other files are strain- and condition specific enzyme-constrained versions, following [this manuscript](https://www.biorxiv.org/content/10.1101/796722v5). Thank you for bringing this up, it is indeed not obvious, we'll soon add a README with instructions.

**Comment by smoretti** [comment]
Thanks
