### ISSUE TITLE
doc: delete gitter repo and update related docs

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#124]
### Description of the issue:
With the newly added Discussion feature on GitHub I don't see the need for an additional gitter repository.  I therefore suggest that we delete that repository and edit our issue templates / documentation / badges to remove any pointers to gitter.

#### To Do
- [x] Post on current  [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM) that discussions are moved here
- [x] Update readme
- [x] Update issue template

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by sulheim** [comment]
closed by #125

**Comment by edkerk** [comment]
FYI, I found out that if the issue is mentioned in the PR to `master` (and it will be in #122), then it will automatically be closed when merged.
