### ISSUE TITLE
chore: add model id

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#128]
### Description of the issue:
I'm tired of getting the warning: `'' is not a valid SBML 'SId'.` every time I read in Sco-GEM. As dash ("-") is not valid SBML I suggest to add the id *Sco_GEM*

#### Expected feature/value/output:
No error message.

#### Reproducing these results:
*If applicable, please attach any code used below (if it's matlab code replace the word "python" with "matlab".*
```python
cobra.io.read_sbml_model("Sco-GEM.xml")
```

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [x] Add id with model.id = "Sco_GEM"

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by edkerk** [comment]
I suggest we append the version number: "Sco_GEM_v1.2.1", `increaseVersion.py` can then increase this with each release (see #118)

**Comment by edkerk** [comment]
Model version should only be included in the `master` branch, as intermediate models in the `devel` and child branches would not correspond to that version number anymore. So will add the model ID without versioning in `devel` and start including the version number when making release v1.3.0.

**Comment by sulheim** [comment]
Sounds good
