### ISSUE TITLE
Memote shows no biomass production

### ISSUE THREAD

**Issue by sammhall** [SysBioChalmers/Sco-GEM#149]
### Describe the bug
When the Memote report was created (after the sbml was put through MetaNetX to align with our naming infrastructure), the growth rate was 0.00 as calculated from 10 individual reactions in the “biomass production in default production” section of the report. Is this expected? Do the authors have any suggestion on how to address this result? 

When Memote was run with the original sbml from GitHub, the Memote wouldn't pass the consistency step. The screenshots below are from the MetaNetX version.

## Software and OS info
Memote version 0.13.0

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [X] E.g. query relevant database
- [X] E.g. generate script for performing curation

**I hereby confirm that:**
- [X] This problem persists in the `master` branch of the repository
- [X] A similar issue does not already exist
- [X] I've considered asking this first in the [Discussion forum](https://github.com/SysBioChalmers/Sco-GEM/discussions)

<img width="554" alt="Screen Shot 2022-06-22 at 7 14 28 AM" src="https://user-images.githubusercontent.com/107962642/175051870-645e21a1-d9b3-4692-bbc8-c3e9dae1e49e.png">
<img width="548" alt="Screen Shot 2022-06-22 at 7 14 02 AM" src="https://user-images.githubusercontent.com/107962642/175051882-597e975b-68fa-44fe-9565-40f8e924f2a4.png">

**Comment by sulheim** [comment]
Hi @sammhall and thanks for your interest in Sco-GEM. The concistency errors in Sco-GEM are mostly related to two aspects: 1) Pseudo-metabolites (e.g. __cellwall_c__) used in pseudo-reactions (such as __CELL_WALL_PSEUDO__); and 2) Secondary metabolism where the metabolic formulas / reactions are not perfectly characterized in the literature / databases (at least when Sco-GEM was initially developed). Indeed, it would be good to make an effort to mass-balance all reactions. 

Regarding the 0.0 growth rate, this is weird and probably an error introduced when converted to MetaNetX. The biomass production in default medium should be 0.07, as you can see in the memote report here: https://sysbiochalmers.github.io/Sco-GEM/snapshot.html

**Comment by sammhall** [comment]
Hello @sulheim, thank you for your response! 
When ran with the original sbml posted here, I was able to get the same number (0.07) for biomass production in default medium. Thanks for your help.
