### ISSUE TITLE
feat: additional annotations

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#44]
### Description of the issue:
Some additional information currently only available in spreadsheets should be added as annotations to the reactions:
- doi annotations (https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000019)
- Confidence scores / evidence annotation (https://github.com/draeger-lab/ModelPolisher/issues/5)

Also, from iAA1259 they have:
 - gene annotation has been expanded to Gene Ontology, Ensembl, and RefSeq
- Protein information (UniProt, Pfam, and Panther) and key reference data, such as protein sequence, length, and mass

I am not sure how this information should be stored, one option is to add the e.g. gene annotations into the SBML-file, and keep protein annotations as a separate csv-file in the ComplementaryData folder

#### To do:
- [x] Gather doi information from iAA1259, Sco4 and iKS1317
- [x] Add doi annotations to model
- [ ] Evidence based annotation (when implemented in cobrapy)
- [x] Add gene annotations from iAA1259
- [x] Upload protein information to repo / or store in a different way

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist

**Comment by edkerk** [comment]
All points except confidence scores are now addressed. As (I) cobrapy does not (yet) support confidence scores; (ii) gathering such scores is quite tedious; and (iii) there is no immediate strong gain from having the scores included in the model, this issue will be closed when the other changes are pulled into `master`. A separate issue could be opened for confidence scores if desired and feasible.
