### ISSUE TITLE
feat: review reaction bounds

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#54]
Use eQuilibrator or metacyc to evaluate and update the bounds of reactions

### Description of the issue:
There is little or no information in previous models on why reactions are set to be reversible or irreversible. Therefore, it would be interesting to use estimated values for the change in Gibbs free energy to reconsider the bounds of all reactions.
A rule of thumb is to use +- 30 dG as the threshold.

#### Expected feature/value/output:
Model with updated bounds

#### To do:
- [x] Get data from eQuilibrator and / or metacyc
- [x] Compare values with current reaction bounds
- [x] Curate / QC proposed changes
- [x] Generate script for performing curation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist

**Comment by sulheim** [comment]
I'm reopening this issue to add a couple of changes to the reaction reversibility:
1) Reaction CPKS4a and CPKS4b in the final stage of the coelimycin pathway should be forward only to avoid loops
2) Set forward direction for clearly atp-driven reaction (as suggested in reconstruction protocol by  Thiele and Palsson https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3125167/). The list is including all reactions where atp is participating, but which is reversible in the model. I suggest to keep nucleoside-diphosphate (NDPK*) reactions and a few others reversible.

Reaction ID | Reaction | Task
------------  | --------- | -------
ADNCYC | atp_c <=> camp_c + ppi_c | Forward
GALKr | atp_c + gal_aD_c <=> adp_c + gal1p_c + h_c | Forward
PGK | 3pg_c + atp_c <=> 13dpg_c + adp_c | Forward
PYK | adp_c + h_c + pep_c <=> atp_c + pyr_c | Forward
CYTK2 | atp_c + dcmp_c <=> adp_c + dcdp_c | Forward
PRPPS | atp_c + r5p_c <=> amp_c + h_c + prpp_c | Forward
CDPMEK | 4c2me_c + atp_c <=> 2p4c2me_c + adp_c + h_c | Forward
NDPK9 | atp_c + idp_c <=> adp_c + itp_c | Keep reversible
CBIAT | atp_c + cbi_c + h_c <=> adocbi_c + pppi_c | Forward
UGMDDS | alaala_c + atp_c + ugmd_c <=> adp_c + h_c + pi_c + ugmda_c | Forward
DBTS | atp_c + co2_c + dann_c <=> adp_c + dtbt_c + 3.0 h_c + pi_c | Forward
DPCOAK | atp_c + dpcoa_c <=> adp_c + coa_c + h_c | Forward
PTPATi | atp_c + h_c + pan4p_c <=> dpcoa_c + ppi_c | Forward
ADNK1 | adn_c + atp_c <=> adp_c + amp_c + h_c | Forward
SHKK | atp_c + skm_c <=> adp_c + h_c + skm5p_c | Forward
PACCOAL | atp_c + coa_c + pac_c <=> amp_c + phaccoa_c + ppi_c | Forward
CBLAT | atp_c + cbl1_c + h_c <=> adocbl_c + pppi_c | Forward
ACS | ac_c + atp_c + coa_c <=> accoa_c + amp_c + ppi_c | Forward
D5KGK | atp_c + d5kg_c <=> adp_c + d5kgp_c + h_c | Forward
MCCC | 3mb2coa_c + atp_c + hco3_c <=> 3mgcoa_c + adp_c + h_c + pi_c | Forward
DHAK | atp_c + dha_c <=> adp_c + dhap_c + h_c | Forward
ACS2 | atp_c + coa_c + ppa_c <=> amp_c + ppcoa_c + ppi_c | Forward
UMPK | atp_c + ump_c <=> adp_c + udp_c | Forward
CBPS | 2.0 atp_c + gln__L_c + h2o_c + hco3_c <=> 2.0 adp_c + cbp_c + glu__L_c + 2.0 h_c + pi_c | Forward
NMNAT | atp_c + h_c + nmn_c <=> nad_c + ppi_c | Forward
ALALAC | ala__D_c + atp_c + lac__D_c <=> adp_c + alalac_c + h_c + pi_c | Forward
TMDK1 | atp_c + thymd_c <=> adp_c + dtmp_c + h_c | Forward
PYDXK | atp_c + pydx_c <=> adp_c + h_c + pydx5p_c | Forward
ASPK | asp__L_c + atp_c <=> 4pasp_c + adp_c | Forward
BUTCOAL | atp_c + butanoate_c + coa_c <=> amp_c + btcoa_c + ppi_c | Forward
NDPK5 | atp_c + dgdp_c <=> adp_c + dgtp_c | Keep reversible
UAMAS | ala__L_c + atp_c + uamr_c <=> adp_c + h_c + pi_c + uama_c | Forward
PPDK | atp_c + pi_c + pyr_c <=> amp_c + h_c + pep_c + ppi_c | Reversible
PYDXNK | atp_c + pydxn_c <=> adp_c + h_c + pdx5p_c | Forward
RMK | atp_c + rml_c <=> adp_c + h_c + rml1p_c | Forward
NDPK6 | atp_c + dudp_c <=> adp_c + dutp_c | Keep reversible
PPCK | atp_c + oaa_c <=> adp_c + co2_c + pep_c | Forward
NDPK7 | atp_c + dcdp_c <=> adp_c + dctp_c | Keep reversible
PFK_2 | atp_c + tag6p__D_c <=> adp_c + h_c + tagdp__D_c | Forward
SUCOAS | atp_c + coa_c + succ_c <=> adp_c + pi_c + succoa_c | Forward
PYDAMK | atp_c + pydam_c <=> adp_c + h_c + pyam5p_c | Forward
PPK2r | atp_c + ppi_c <=> adp_c + pppi_c | Forward
NDPK8 | atp_c + dadp_c <=> adp_c + datp_c | Keep reversible
NDPK1 | atp_c + gdp_c <=> adp_c + gtp_c | Keep reversible
PMPK | 4ampm_c + atp_c <=> 2mahmp_c + adp_c | Forward
DGK1 | atp_c + dgmp_c <=> adp_c + dgdp_c | Forward
ADK1 | amp_c + atp_c <=> 2.0 adp_c | Forward
XYLK2 | atp_c + xylu__L_c <=> adp_c + h_c + xu5p__L_c | Forward
ACTCOALIG | ac_c + atp_c + coa_c <=> accoa_c + adp_c + pi_c | Forward
DADK | atp_c + damp_c <=> adp_c + dadp_c | Keep reversible
ADSK | aps_c + atp_c <=> adp_c + h_c + paps_c | Forward
HEX4 | atp_c + man_c <=> adp_c + h_c + man6p_c | Forward
NDPK2 | atp_c + udp_c <=> adp_c + utp_c | Keep reversible
UAMAGS | atp_c + glu__D_c + uama_c <=> adp_c + h_c + pi_c + uamag_c | Forward
GLU5K | atp_c + glu__L_c <=> adp_c + glu5p_c | Forward
PNTK | atp_c + pnto__R_c <=> 4ppan_c + adp_c + h_c | Forward
NDPK3 | atp_c + cdp_c <=> adp_c + ctp_c | Keep reversible
KHK2 | atp_c + xylu__L_c <=> adp_c + xu1p__D_c | Forward
PRAGSr | atp_c + gly_c + pram_c <=> adp_c + gar_c + h_c + pi_c | Forward
SUCBZL | atp_c + coa_c + sucbz_c <=> amp_c + ppi_c + sbzcoa_c | Forward
UAAGDS | 26dap__M_c + atp_c + uamag_c <=> adp_c + h_c + pi_c + ugmd_c | Forward
NDPK4 | atp_c + dtdp_c <=> adp_c + dttp_c | Keep reversible
XYLK | atp_c + xylu__D_c <=> adp_c + h_c + xu5p__D_c | Forward
ACKr | ac_c + atp_c <=> actp_c + adp_c | Forward
DTMPK | atp_c + dtmp_c <=> adp_c + dtdp_c | Keep reversible
CTPS1 | atp_c + nh4_c + utp_c <=> adp_c + ctp_c + 2.0 h_c + pi_c | Forward
MMCOAL | atp_c + coa_c + mmal_c <=> amp_c + mmcoa__R_c + ppi_c | Forward
FACOAL160 | atp_c + coa_c + hdca_c <=> amp_c + pmtcoa_c + ppi_c | Forward
FMNAT | atp_c + fmn_c + h_c <=> fad_c + ppi_c | Forward
HPPK2 | 6hmhpt_c + atp_c <=> 6hmhptpp_c + amp_c + h_c | Forward
HMPK1 | 4ahmmp_c + atp_c <=> 4ampm_c + adp_c + h_c | Forward
GLGC | atp_c + g1p_c + h_c <=> adpglc_c + ppi_c | Forward
DURIK1 | atp_c + duri_c <=> adp_c + dump_c + h_c | Forward
CYTDK1 | atp_c + cytd_c <=> adp_c + cmp_c + h_c | Forward
LTHRK | atp_c + thr__L_c <=> adp_c + h_c + thrp_c | Forward
ACGAMK | acgam_c + atp_c <=> acgam6p_c + adp_c + h_c | Forward
MACPAL | atp_c + gln__L_c + h2o_c + malACP_c <=> amp_c + glu__L_c + 2.0 h_c + malmoACP_c + ppi_c | Forward
GK1i | atp_c + gmp_c <=> adp_c + gdp_c | Forward
DDGLK | 2ddglcn_c + atp_c <=> 2ddg6p_c + adp_c + h_c | Forward
RBFK | atp_c + ribflv_c <=> adp_c + fmn_c + h_c | Forward
GLCOAS | atp_c + coa_c + glutar_c <=> adp_c + glutcoa_c + pi_c | Forward
MALTHIK | atp_c + coa_c + mal__L_c <=> adp_c + malylcoa_c + pi_c | Forward
CYTK1 | atp_c + cmp_c <=> adp_c + cdp_c | Keep reversible

**Comment by sulheim** [comment]
The model accuracy should be re-calculated to see that we don't make it worse.

**Comment by edkerk** [comment]
Makes sense to me, but what where their dG-values by any change close to -30? In that case, would moving that cutoff be a reasonable approach?

**Comment by sulheim** [comment]
Updated the table @edkerk

**Comment by sulheim** [comment]
To avoid making to strict constraints I have update the decision (Task - column) according to the following heuristics:
All ATP-driven reactions are forward unless
- Estimated positive dG
- nucleoside-diphosphate kinase (known to be reversible)
