### ISSUE TITLE
docs: link repo to Zenodo

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#65]
### Description of the issue:
To ensure future data availability we want to store a snapshot of the repository on [Zenodo](https://zenodo.org/) on every new release of the model.
 More information on how to do this is given her
https://guides.github.com/activities/citable-code/

**I hereby confirm that:**
- [x] A similar issue does not already exist

**Comment by edkerk** [comment]
This is switched on at Zenodo, when a new release is made on GitHub it will start tracking and only then a DOI will be assigned that can subsequently be included in the documentation.
