### ISSUE TITLE
fix: direction of ICDhyr (isocitrate dehydrogenase)

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#87]
### Description of the issue:
The reaction ICDhyr [R00267](https://www.genome.jp/dbget-bin/www_bget?rn:R00267+R01899+R00268) is actually a two-step reaction where the second step is irreversible (dG of -32 kJ/mmol). The reaction combined has a dG of -10, and it is therefor set to reversible, which is not true.

#### Expected feature/value/output:
The optimal solution is to replace ICDhyr by the two reactions and make the second reaction irreversible. Another option is to just make the ICDhyr irreversible.

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [x] Decide on a solution and make changes to the reconstruction script
- [x] Update model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by edkerk** [comment]
Making the reaction irreversible should be sufficient? Could also mention the reason for this in the reaction note (does cobrapy have `rxnNotes` as part of the model?).

**Comment by sulheim** [comment]
Agree. Yes, cobrapy can write notes now, so that sounds like a good solution. 

There is no version of the reaction with NADH.
