### ISSUE TITLE
fix: alpha and beta variants of glucose-6-phosphate 

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/Sco-GEM#89]
There is currently 3 versions of glucose-6-phosphate in the model:
- General form g6p_c (In 10 reactions)
- Beta form g6p_B_c (In 6 reactions)
- Alpha form g6p_A_c (In 2 reactions)

From [HMDB](http://www.hmdb.ca/metabolites/HMDB0003498) we have *... Specifically, beta-D-Glucose 6-phosphate is glucose sugar phosphorylated on carbon 6. It is a very common metabolite in cells as the vast majority of glucose entering a cell will become phosphorylated in this way.*

### Description of the issue:
It is currently a bit messy to have all three variants. We can either:
1) Use only the general form (g6p_c)
2) Use both the the alpha and beta form (But then what form should the currently general form be assigned to?
3) Keep all of them and have isomerases between all the three pairs (currently only between g6p_A_c and g6p_B_c)

This differences propagates to some extent into fructose 6-phosphate and maybe a few other compounds. 

#### Expected feature/value/output:
A clean, tidy solution which reduce unnecessary mess while keeping important details.

#### To do:
- [ ] Agree on a solution for glucose 6-phosphate and a general solution for similar issues
- [ ] Find out which reactions and which related compounds that are affected
- [ ] Generate script for performing curation and update model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

**Comment by edkerk** [comment]
I'd vote for using only the general form.
